name: terraform-plan

on: [pull_request]

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AGUSTIN_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_AGUSTIN_SECRET }}

jobs:

        ejecucion-plan:
            runs-on: ubuntu-latest

            steps:
            - uses: actions/checkout@v4            
            - run: terraform init
            - run: terraform plan
            - run: 
                 echo Se ha ejecutado un terraform plan
